### ISSUE TITLE
Noob questions: setting up

### ISSUE THREAD

**Issue by axodentally** [Hashik-Donthineni/Docker-snowflake-proxy#1]
Hi, so I am a little new to docker and all of this, but I found this image quite interesting. I am running traefik as a reverse proxy, and pihole as dns server (thats why cloudflare dns is in there, since I had some probelems with docker containers and pihole as dns) but I assume that this is irrelevant, since I do not need to open up any ports for snowflake, right?

So this is my docker compose file:
```
version: "3"

services:
  snowflake-proxy:
    image: thetorproject/snowflake-proxy:latest
    container_name: snowflake-proxy
    dns: 1.1.1.1
    network_mode: host
    restart: always
```

The console says:
```
Recreating snowflake-proxy ... done                                                                                     
Attaching to snowflake-proxy
snowflake-proxy    | 2020/07/24 18:22:44 starting
snowflake-proxy    | 2020/07/24 18:22:55 NAT type: restricted
```

thanks for any help :)
